### ISSUE TITLE
test h7-rom in h6!

### ISSUE THREAD

**Issue by GavinAndrews** [vossi1/2001test#1]
Burnt to 2716 and adapted to Socket H7 ($F800-$FFFF) when run seems to say "test h7-rom in h6!" but currently my H6 is unpopulated. H6 is $D800-$DFFF so I cannot see how the test ROM could possibly be in h6?

(Great project.... really helping in my diagnosis of my first PET restore)

**Comment by vossi1** [comment]
It tests the checksum of original basic 1 and revised basic roms in their specific sockets h1-h6.
But you can plug your h7 rom in the h6 socket and it checks there the checksum of it.
You cannot test the h7 rom in the h7 socket because there is the test-eprom ;)

**Comment by GavinAndrews** [comment]
Ah.... it is an instruction?  i.e. to test H7 put in H6?

H6 is not mapped to $FFFC so how would that work?  H6 is D800-DFFF

**Comment by vossi1** [comment]
Yes its an instruction. The 2k rom is full I have not much space for big explanations ;)
The test checks only the checksum of the rom in this socket. It runs only the test program from me in socket h7. It uses only the socket h6.

**Comment by GavinAndrews** [comment]
Aha!  I'm with you now...

So test rom always in H7 but you can test the ROM you took out of H7 by putting it in H6!

I did that and got a H6 $A6 018 OK

Perfect.  Thanks for a great project.
